### ISSUE TITLE
text stroke not working on web

### ISSUE THREAD

**Issue by kervishalsinh** [tewshi/bordered-text#6]
**text stroke completely working on android ios but not working on web.**

![Screenshot 2020-02-25 at 2 49 44 PM](https://user-images.githubusercontent.com/55441927/75232993-24cd1e00-57de-11ea-8535-08bac3405608.png)

**Comment by dennym** [comment]
Known issue flutter/flutter#46683

**Comment by dhiyaaulauliyaa** [comment]
Does anybody have a solution for this issue? have the exactly same problem here, doesn't work on the web.

**Comment by tewshi** [comment]
looking into is, I believe once the issue at flutter/flutter#46683 as referenced by @dennym is resolved, this will be resolved too.

**Comment by casetofon** [comment]
I mean.. just remove the 'web' tag from the plugin. It would spare some people the time it takes to figure out it's not working.

**Comment by tewshi** [comment]
Thanks, I've been looking for how to remove the web tag, any idea?

**Comment by tewshi** [comment]
@casetofon

**Comment by tewshi** [comment]
I just noticed that, Flutter only has support for web on it's Beta channel.

**Comment by tewshi** [comment]
finally, this is resolved, and i'll push an updated version in a bit.

**Comment by OscarGarPer** [comment]
I know this is closed but I have found that this plugin works on desktop web browsers, but not on android and iOS browsers. I distribute my app as a PWA, on  windows chrome it works perfectly, but on android and iOS, installed from browsers as a PWA the border of the text isn't shown.

**Comment by tewshi** [comment]
Please, can you create an issue with this, I have not tested this on mobile web, didn't think it will be an issue.

**Comment by OscarGarPer** [comment]
Ok. I though it was the same issue. I will create a new one and add some screenshots. Regards!

**Comment by tewshi** [comment]
Thanks @OscarGarPer

**Comment by abelokon0711** [comment]
This does not work if one uses the web renderer (default renderer on mobile devices):

`flutter run -d chrome -web-renderer html`

**Comment by tewshi** [comment]
Okay, I see.

**Comment by tewshi** [comment]
flutter run -d chrome --web-renderer html

looks like the command you dropped is missing a second hyphen @abelokon0711
